# ansible-role-swarm-initialization/tasks/main.yml

- name: Initialize Docker Swarm on the first manager
  ansible.builtin.shell: >
    docker swarm init --advertise-addr {{ ansible_host }}:2377
    --default-addr-pool 172.80.0.0/16 --default-addr-pool-mask-length 24
  when: inventory_hostname == groups['managers'][0]
  register: swarm_init_output
  changed_when: "'This node is already part of a swarm' not in swarm_init_output.stderr"

- name: Get manager join token
  ansible.builtin.command: docker swarm join-token manager -q
  when: inventory_hostname == groups['managers'][0]
  register: manager_token
  changed_when: false

- name: Get worker join token
  ansible.builtin.command: docker swarm join-token worker -q
  when: inventory_hostname == groups['managers'][0]
  register: worker_token
  changed_when: false

- name: Join additional managers to the swarm
  ansible.builtin.command: >
    docker swarm join --token {{ hostvars[groups['managers'][0]].manager_token.stdout }}
    --advertise-addr {{ ansible_host }}:2377 {{ hostvars[groups['managers'][0]].ansible_host }}:2377
  when:
    - inventory_hostname != groups['managers'][0]
    - inventory_hostname in groups['managers']
  check_mode: false
  changed_when: false

- name: Join workers to the swarm
  ansible.builtin.command: >
    docker swarm join --token {{ hostvars[groups['managers'][0]].worker_token.stdout }}
    {{ hostvars[groups['managers'][0]].ansible_host }}:2377
  when: inventory_hostname in groups['workers']
  check_mode: false
  changed_when: false

- name: Verify members of the swarm
  ansible.builtin.command: docker node ls
  register: swarm_members
  when: inventory_hostname == groups['managers'][0]
  check_mode: false
  changed_when: false

- name: Display swarm members
  ansible.builtin.debug:
    var: swarm_members.stdout
  when: inventory_hostname == groups['managers'][0]

- name: Test network connection from Docker container
  ansible.builtin.shell: >
    docker run -it --rm busybox ping -c5 google.com
  register: network_test
  when: inventory_hostname == groups['managers'][0]
  check_mode: false
  changed_when: false

- name: Display network test results
  ansible.builtin.debug:
    var: network_test.stdout
  when: inventory_hostname == groups['managers'][0]

- name: Create Docker visualizer service
  ansible.builtin.command: >
    docker service create
    --name=viz
    --publish=8080:8080/tcp
    --constraint=node.role==manager
    --mount=type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock
    alexellis2/visualizer-arm:latest
  when: inventory_hostname == groups['managers'][0]
  changed_when: false

- name: Check Docker services
  ansible.builtin.command: docker service ls
  register: service_status
  when: inventory_hostname == groups['managers'][0]
  check_mode: false
  changed_when: false

- name: Display service status
  ansible.builtin.debug:
    var: service_status.stdout
  when: inventory_hostname == groups['managers'][0]
  check_mode: false
  changed_when: false
